# Generated by Django 5.0 on 2024-09-27 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainSystem', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
