# Generated by Django 5.0 on 2024-10-08 03:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSystem', '0002_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='darstantashqaritadbirlar',
            options={'verbose_name': 'Darsdan tashqari tadbir', 'verbose_name_plural': 'Darsdan tashqari tadbirlar'},
        ),
        migrations.AlterField(
            model_name='darstantashqaritadbirlar',
            name='maqola',
            field=models.FileField(upload_to='darsdan_tashqari_files/', verbose_name="Darsdan tashqari madaniy va ma'rifiy tadbir"),
        ),
        migrations.AlterField(
            model_name='oqitishsifati',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, editable=False, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(3.0)], verbose_name='Umumiy ball'),
        ),
        migrations.AlterField(
            model_name='oqitishsifati',
            name='talim_sifat',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='talabalardan o‘tkazilgan so‘rovnomalar natijalari bo‘icha'),
        ),
        migrations.AlterField(
            model_name='oqitishsifati',
            name='talim_sifat_xulosasi',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(3.0)], verbose_name="ta'lim sifatini nazorat qilish bo‘limi xulosasi bo‘yicha"),
        ),
    ]
