# Generated by Django 5.0 on 2024-10-08 06:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSystem', '0003_alter_darstantashqaritadbirlar_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktdasturlar',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(3.0)], verbose_name='Baholash'),
        ),
        migrations.AlterField(
            model_name='axborotmurobbiyliksoat',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(3.0)], verbose_name='Baholash'),
        ),
        migrations.AlterField(
            model_name='birziyolibirmahalla',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(5.0)], verbose_name='Baholash'),
        ),
        migrations.AlterField(
            model_name='darslikyokiqollanma',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(50.0)], verbose_name='Baholash'),
        ),
        migrations.AlterField(
            model_name='darstantashqaritadbirlar',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(4.0)], verbose_name='Baholash'),
        ),
        migrations.AlterField(
            model_name='dissertationhimoya',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(100.0)], verbose_name='Baholash'),
        ),
        migrations.AlterField(
            model_name='fanvideokontent',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(8.0)], verbose_name='Baholash'),
        ),
        migrations.AlterField(
            model_name='faolinterfaolmetodlar',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(4.0)], verbose_name='Baholash'),
        ),
        migrations.AlterField(
            model_name='hindex',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(5.0)], verbose_name='Baholash'),
        ),
        migrations.AlterField(
            model_name='horijdamalakaoshirish',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(100.0)], verbose_name='Baholash'),
        ),
        migrations.AlterField(
            model_name='ilmiyrahbarlik',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(100.0)], verbose_name='Baholash'),
        ),
        migrations.AlterField(
            model_name='konferensiyamaqola',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(2.0)], verbose_name='Baholash'),
        ),
        migrations.AlterField(
            model_name='loyihalartayyorlash',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(5.0)], verbose_name='Baholash'),
        ),
        migrations.AlterField(
            model_name='loyihamoliya',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(6.0)], verbose_name='Baholash'),
        ),
        migrations.AlterField(
            model_name='muhimtashabbuslarishlari',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(3.0)], verbose_name='Baholash'),
        ),
        migrations.AlterField(
            model_name='mustaqiltalimtopshiriqlari',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(4.0)], verbose_name='Baholash'),
        ),
        migrations.AlterField(
            model_name='nashretilgandarsliklar',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(6.0)], verbose_name='Baholash'),
        ),
        migrations.AlterField(
            model_name='oakjurnalimaqola',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(5.0)], verbose_name='Baholash'),
        ),
        migrations.AlterField(
            model_name='oqitishsifati',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, editable=False, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(6.0)], verbose_name='Umumiy ball'),
        ),
        migrations.AlterField(
            model_name='oqitishsifati',
            name='talim_sifat',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(3.0)], verbose_name='talabalardan o‘tkazilgan so‘rovnomalar natijalari bo‘icha'),
        ),
        migrations.AlterField(
            model_name='oquvyilifanlar',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(2.0)], verbose_name='Baholash'),
        ),
        migrations.AlterField(
            model_name='otaonalarishlash',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(3.0)], verbose_name='Baholash'),
        ),
        migrations.AlterField(
            model_name='scopuswebofscience',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(15.0)], verbose_name='Baholash'),
        ),
        migrations.AlterField(
            model_name='talabailmiyfaoliyati',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(5.0)], verbose_name='Baholash'),
        ),
        migrations.AlterField(
            model_name='talabalarturarjoytadbirlar',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(3.0)], verbose_name='Baholash'),
        ),
        migrations.AlterField(
            model_name='tarbiyatadbirlar',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(3.0)], verbose_name='Baholash'),
        ),
    ]
