# Generated by Django 5.0 on 2024-10-21 10:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSystem', '0003_alter_fanvideokontent_max_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fanvideokontent',
            name='max_score',
        ),
        migrations.AddField(
            model_name='fanvideokontent',
            name='max_score_value',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Max Score Value'),
        ),
        migrations.AlterField(
            model_name='fanvideokontent',
            name='izoh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fanvideokontent',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(8.0), django.core.validators.MinValueValidator(0.0)], verbose_name='Baholash'),
        ),
        migrations.CreateModel(
            name='MaxScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_score', models.DecimalField(decimal_places=1, max_digits=5)),
                ('score_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='max_scores', to='mainSystem.fanvideokontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
