# Generated by Django 5.0 on 2024-10-21 10:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mainSystem', '0004_remove_fanvideokontent_max_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maxscore',
            name='score_for',
        ),
        migrations.AddField(
            model_name='maxscore',
            name='content_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maxscore',
            name='object_id',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maxscore',
            name='max_score',
            field=models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
